fe: ""
emission_lines: ""
## Host Galaxy parameters##
host_galaxy:
    hg_models: "/user/jotaylor/git/spamm/Data/HostModels" #dir
    hg_norm_min: 0.
    hg_norm_max: "max_flux"
    hg_stellar_disp_min: 0.
    hg_stellar_disp_max: ?

## Boxcar width to use when calculating running mean ##
boxcar_width: 5

## NuclearContnuumComponent power law parameters ##
nuclear_continuum:
    broken_pl: False 
    pl_slope_min: -3.
    pl_slope_max: 3.
    pl_norm_min: 0.
    pl_norm_max: "max_flux"
    pl_wave_break_min: "min_wl"
    pl_wave_break_max: "max_wl"
    #pl_par_prior: np.random.uniform

