fe: ""
emission_lines: ""
## Host Galaxy parameters##
host_galaxy:
    boxcar_width: 5
    hg_templates: "../Templates/Host_templates"
    hg_norm_min: 0.0
    hg_norm_max: "max_flux"
    hg_stellar_disp_min: 30.
    hg_stellar_disp_max: 1000.
    hg_template_stellar_disp: 0.0
    hg_kernel_size_sigma: 10

## Boxcar width to use when calculating running mean ##
boxcar_width: 5

## NuclearContnuumComponent power law parameters ##
nuclear_continuum:
    boxcar_width: 5
    broken_pl: False 
    pl_slope_min: -3.
    pl_slope_max: 3.
    pl_norm_min: 0.
    pl_norm_max: "max_flux"
    pl_wave_break_min: "min_wl"
    pl_wave_break_max: "max_wl"
    #pl_par_prior: np.random.uniform

balmer_continuum:
    bc_lines_min: 3
    bc_lines_max: 50
    bc_line_type: "lorentzian"