channels:
- http://ssb.stsci.edu/astroconda
- defaults
- astropy
dependencies:
- python=3.7
- astropy>=3.1.2
- dill>=0.2.9
- matplotlib>=3.0.3
- numpy>=1.16.2
- pyfftw>=0.9.2
- scipy>=1.2.1
- specutils>=0.5.2
- yaml>=0.1.7
- pip: 
  - emcee>=2.2.1
  - sphinx_rtd_theme>=0.4.3
